name: daily-cron2
on:
  schedule:
    - cron: '26 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://pptrbd.vercel.app/uplinks'

        - name: Use the value
         run: |
          curl --request GET \
          --url 'https://nodebd.vercel.app/cheak_down_links'

