name: daily-cron
on:
  schedule:
    - cron: '49 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://pptrbd.vercel.app/uplinks'

