name: daily-cron2
on:
  schedule:
    - cron: '33 * * * *'
jobs:
  first_job:
    cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://pptrbd.vercel.app/uplinks'


