name: daily-cron
on:
  schedule:
    - cron: '38 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://pptrbd.vercel.app/uplinks'

      # - name: Call our API route2
      #   run: |
      #     curl --request GET \
      #     --url 'https://nodebd.vercel.app/cheak_down_links'
