# name: daily-cron
# on:
#   schedule:
#     - cron: '35 * * * *'
# jobs:
#   cron:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Call our API route
#         run: |
#           curl --request GET \
#           --url 'https://nodebd.vercel.app/chatdatanoti'
